name: Collect Schumann

on:
  schedule:
    - cron: "*/30 * * * *"   # каждые 30 минут
  workflow_dispatch:

permissions:
  contents: write  # чтобы коммитить в репозиторий

concurrency:
  group: collect-schumann
  cancel-in-progress: false

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Если есть requirements.txt — раскомментируй установку
      # - name: Install deps
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # ВАЖНО: тут предполагается, что collect_schumann.py уже лежит в корне репо.
      # Если он в подкаталоге — поправь путь.
      - name: Run collector
        run: |
          python collect_schumann.py

      - name: Show last row
        run: |
          tail -n 1 schumann_hourly.json || true
          echo "File size:"
          wc -c schumann_hourly.json || true

      # Коммитим ТОЛЬКО если файл реально изменился
      - name: Commit & push if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet -- schumann_hourly.json; then
            git add schumann_hourly.json
            git commit -m "schumann: update (ver2: ts,freq,amp,h7_amp,h7_spike)"
            git push
          else
            echo "No changes in schumann_hourly.json"
          fi
