name: Collect SafeCast (Kaliningrad)

on:
  schedule:
    - cron: "0 */6 * * *"   # каждые 6 часов
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Fetch SafeCast (Kaliningrad)
        run: |
          set -e
          mkdir -p data
          OUT_FILE="data/safecast_kaliningrad.json"
          python safecast.py \
            --lat 54.7104 \
            --lon 20.4522 \
            --dist 300 \
            --hours 48 \
            --out "$OUT_FILE"

      - name: Preview file (size, JSON, ts → ISO)
        run: |
          set -e
          FILE="data/safecast_kaliningrad.json"
          if [ -f "$FILE" ]; then
            echo "::group::File info"
            ls -lah "$FILE"
            echo "::endgroup::"

            echo "::group::Pretty JSON"
            python - <<'PY'
import json, sys, os
from datetime import datetime, timezone
p = "data/safecast_kaliningrad.json"
with open(p, "r", encoding="utf-8") as f:
    d = json.load(f)
print(json.dumps(d, ensure_ascii=False, indent=2))
ts = d.get("ts")
if isinstance(ts, (int, float)):
    print("ts_iso:", datetime.fromtimestamp(int(ts), tz=timezone.utc).isoformat())
else:
    print("ts_iso: n/a")
print("keys:", list(d.keys()))
PY
            echo "::endgroup::"
          else
            echo "File not found: $FILE"
            exit 1
          fi

      - name: Commit & Push if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # безопасный pull с автозастэшем
          git pull --rebase --autostash

          if [ -n "$(git status --porcelain -- data/safecast_kaliningrad.json)" ]; then
            git add data/safecast_kaliningrad.json
            git commit -m "safecast(Kaliningrad): update data/safecast_kaliningrad.json"
            git push
          else
            echo "No changes in data/safecast_kaliningrad.json"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: safecast-kaliningrad
          path: data/safecast_kaliningrad.json