name: Collect Schumann

on:
  schedule:
    - cron: "*/30 * * * *"     # каждые 30 минут
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: collect-schumann
  cancel-in-progress: false

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run collector (writes schumann_hourly.json v2)
        env:
          # — HeartMath (GCI)
          SCHU_GCI_ENABLE: "1"
          SCHU_GCI_STATIONS: "GCI001,GCI003,GCI006,GCI004,GCI005"
          SCHU_GCI_URL: "https://www.heartmath.org/gci/gcms/live-data/gcms-magnetometer/"
          SCHU_GCI_IFRAME: "https://www.heartmath.org/gci/gcms/live-data/gcms-magnetometer/power_levels.html"
          SCHU_MAP_GCI_POWER_TO_AMP: "1"

          # — файл истории и локальный HTML (если есть)
          SCHU_FILE: schumann_hourly.json
          SCHU_MAX_LEN: "5000"
          SCHU_HEARTMATH_HTML: data/gcms_magnetometer_heartmath.html

          # — базовые настройки
          SCHU_AMP_SCALE: "1"
          SCHU_TREND_WINDOW: "24"
          SCHU_TREND_DELTA: "0.1"
          SCHU_ALLOW_CACHE_ON_FAIL: "1"

          # — опциональный свой JSON-эндпоинт
          SCHU_CUSTOM_URL: ""

          # — 7-я гармоника (зарезервировано)
          H7_URL: ""
          H7_TARGET_HZ: "54.81"
          H7_WINDOW_H: "48"
          H7_Z: "2.5"
          H7_MIN_ABS: "0.2"
        run: |
          python schumann.py --collect
          echo "Last record:"
          tail -n 1 schumann_hourly.json || true
          echo "File size:"
          wc -c schumann_hourly.json || true

      - name: Commit & push if changed (stash-safe rebase)
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Изменился ли файл?
          if git diff --quiet -- schumann_hourly.json; then
            echo "No changes in schumann_hourly.json"
            exit 0
          fi

          # Сохраняем локальные правки, подтягиваем upstream и возвращаем их обратно
          STASHED=0
          git stash push -u -m "schu-auto" || true
          if git stash list | grep -q "schu-auto"; then
            STASHED=1
          fi

          git pull --rebase || true

          if [ "$STASHED" -eq 1 ]; then
            # Попробуем применить; если конфликтов нет — продолжим.
            git stash pop || true
          fi

          # Финальный статус файла
          if git diff --quiet -- schumann_hourly.json; then
            echo "After rebase, nothing to commit."
            exit 0
          fi

          git add schumann_hourly.json
          git commit -m "schumann: update (v2, live GCI power, cache-safe, H7-ready)"
          git push

      - name: Upload artifact (schumann_hourly.json)
        uses: actions/upload-artifact@v4
        with:
          name: schumann-json
          path: schumann_hourly.json
          if-no-files-found: warn
          retention-days: 7