name: Collect SafeCast (Kaliningrad)

on:
  schedule:
    - cron: "0 */6 * * *"     # каждые 6 часов
  workflow_dispatch:
  push:                       # запускаться при ЛЮБОМ коммите
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: safecast-kld
  cancel-in-progress: true

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Sanity check
        run: |
          echo "Ref: $GITHUB_REF  Sha: $GITHUB_SHA  Actor: $GITHUB_ACTOR"
          echo "Runner: $(uname -a)"

      - name: Sync to origin/main (clean base)
        run: |
          set -euo pipefail
          git fetch origin main
          git checkout -B main origin/main
          git reset --hard origin/main
          mkdir -p data

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Fetch SafeCast (Kaliningrad)
        run: |
          set -euo pipefail
          python safecast.py \
            --lat 54.7104 \
            --lon 20.4522 \
            --dist 300 \
            --hours 48 \
            --out data/safecast_kaliningrad.json

      - name: Preview JSON
        run: |
          set -euo pipefail
          FILE="data/safecast_kaliningrad.json"
          if [ ! -f "$FILE" ]; then
            echo "❌ File not found: $FILE"; exit 1
          fi
          ls -lah "$FILE"
          python - <<'PY'
import json, sys, pathlib, datetime
p=pathlib.Path("data/safecast_kaliningrad.json")
d=json.loads(p.read_text("utf-8"))
print("---- Pretty JSON ----")
print(json.dumps(d, ensure_ascii=False, indent=2))
ts = d.get("ts")
if isinstance(ts,(int,float)):
    print("ts_iso:", datetime.datetime.utcfromtimestamp(int(ts)).isoformat()+"Z")
else:
    print("ts_iso: n/a")
print("keys:", list(d.keys()))
PY

      - name: Commit & push if changed
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain -- data/safecast_kaliningrad.json)" ]; then
            git add data/safecast_kaliningrad.json
            git commit -m "safecast(Kaliningrad): update data/safecast_kaliningrad.json"
            git push origin HEAD:main
          else
            echo "No changes in data/safecast_kaliningrad.json"
          fi

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: safecast-kaliningrad
          path: data/safecast_kaliningrad.json