name: collect-radiation
on:
  schedule:
    - cron:  '0 * * * *'      # каждый час
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: pip install requests
      - name: Run collector
        run: python radiation_collect.py
      - name: Commit cache
        run: |
          git config user.name "rad-bot"
          git config user.email "<>"
          git add radiation_hourly.json
          git commit -m "radiation: hourly update" || echo "no changes"
          git push
