name: 🇷🇺 Kaliningrad daily post

on:
  schedule:
    # 14:00 UTC → 17:00 Asia/Nicosia
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🔍 Проверка сети Schumann и Open-Meteo
        run: |
          echo "=== Проверка Schumann API через зеркала ==="
          # зеркало через CodeTabs
          curl -I https://api.codetabs.com/v1/proxy?quest=https://api.glcoherence.org/v1/earth || true
          # зеркало через Freeboard ThingProxy
          curl -I https://thingproxy.freeboard.io/fetch/https://api.glcoherence.org/v1/earth || true
          # зеркало через AllOrigins
          curl -I https://api.allorigins.win/raw?url=https://api.glcoherence.org/v1/earth || true
          # прямой основной endpoint
          curl -I https://api.glcoherence.org/v1/earth || true
          # второй источник
          curl -I https://gci-api.ucsd.edu/data/latest || true
          echo "---"
          echo "=== Проверка Open-Meteo Forecast ==="
          curl -I "https://api.open-meteo.com/v1/forecast?latitude=34.707&longitude=33.022&hourly=soil_temperature_0cm" || true

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt \
              requests python-dateutil pendulum astropy

      - name: 🚀 Run VayбоМетр poster
        env:
          OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_TOKEN_KLG:  ${{ secrets.TELEGRAM_TOKEN_KLG }}
          CHANNEL_ID_KLG:      ${{ secrets.CHANNEL_ID_KLG }}
          OWM_KEY:         ${{ secrets.OWM_KEY }}
          AIRVISUAL_KEY:   ${{ secrets.AIRVISUAL_KEY }}
          AMBEE_KEY:       ${{ secrets.AMBEE_KEY }}
          COPERNICUS_USER: ${{ secrets.COPERNICUS_USER }}
          COPERNICUS_PASS: ${{ secrets.COPERNICUS_PASS }}
        run: python post_kld.py
