name: Daily VayboMeter (KLD)

on:
  schedule:
    # Вечерний пост: 15:00 UTC (оставляю как в примере)
    - cron: '0 15 * * *'
    # Курсы валют в полдень МСК: 09:00 UTC = 12:00 МСК
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      run_evening:
        description: "Запустить вечерний пост"
        default: "true"
        required: false
      run_noon_fx:
        description: "Запустить пост только с курсами"
        default: "false"
        required: false
      work_date:
        description: "Переопределить дату (YYYY-MM-DD)"
        required: false
      to_test:
        description: "Публиковать в тестовый канал?"
        type: boolean
        default: false
        required: false
      channel_override:
        description: "Явный chat_id канала (перебивает параметры выше)"
        required: false

permissions:
  contents: read

concurrency:
  group: daily-post-klg
  cancel-in-progress: false

# общие переменные окружения для всех джоб
env:
  TELEGRAM_TOKEN_KLG: ${{ secrets.TELEGRAM_TOKEN_KLG }}
  CHANNEL_ID_KLG:     ${{ secrets.CHANNEL_ID_KLG }}
  CHANNEL_ID_TEST:    ${{ secrets.CHANNEL_ID_TEST }}
  # опц. явная переадресация канала из inputs
  CHANNEL_ID_OVERRIDE: ${{ github.event.inputs.channel_override }}
  # вкл/выкл микро-LLM, таймзона, дата для ручного запуска
  OPENAI_API_KEY:     ${{ secrets.OPENAI_API_KEY }}
  GEMINI_API_KEY:     ${{ secrets.GEMINI_API_KEY }}
  GROQ_API_KEY:       ${{ secrets.GROQ_API_KEY }}
  GEN_SKIP_SHORT: "1"
  DISABLE_LLM_DAILY: "0"
  TZ: Europe/Kaliningrad
  WORK_DATE: ${{ github.event.inputs.work_date }}
  # прокинем флаг в скрипт
  TO_TEST: ${{ github.event.inputs.to_test }}

jobs:
  evening:
    name: Evening post (for tomorrow)
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'schedule' && github.event.schedule == '0 15 * * *') ||
      (github.event_name == 'workflow_dispatch' &&
       (!github.event.inputs.run_evening || github.event.inputs.run_evening == 'true'))
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Post daily (announce tomorrow)
        shell: bash
        run: |
          python <<'PY'
          import os, runpy, sys, pendulum
          wd = os.getenv("WORK_DATE")
          if wd:
              def _fake_today(tz=None):
                  dt = pendulum.parse(wd)
                  return dt.in_tz(tz) if tz else dt
              pendulum.today = _fake_today

          args = ["post_kld.py", "--for-tomorrow"]
          # явный override из input — передадим как --chat-id
          chat_override = os.getenv("CHANNEL_ID_OVERRIDE") or ""
          if chat_override.strip():
              args += ["--chat-id", chat_override.strip()]
          else:
              # иначе чекбокс to_test
              to_test = os.getenv("TO_TEST","").strip().lower() in ("1","true","yes","on")
              if to_test:
                  args.append("--to-test")

          sys.argv = args
          runpy.run_path("post_kld.py", run_name="__main__")
          PY

  noon_fx:
    name: Noon FX only (12:00 MSK)
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'schedule' && github.event.schedule == '0 9 * * *') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.run_noon_fx == 'true')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Post FX only (12:00 MSK)
        shell: bash
        run: |
          python <<'PY'
          import os, runpy, sys, pendulum
          wd = os.getenv("WORK_DATE")
          if wd:
              def _fake_today(tz=None):
                  dt = pendulum.parse(wd)
                  return dt.in_tz(tz) if tz else dt
              pendulum.today = _fake_today

          args = ["post_kld.py", "--fx-only"]
          chat_override = os.getenv("CHANNEL_ID_OVERRIDE") or ""
          if chat_override.strip():
              args += ["--chat-id", chat_override.strip()]
          else:
              to_test = os.getenv("TO_TEST","").strip().lower() in ("1","true","yes","on")
              if to_test:
                  args.append("--to-test")
          sys.argv = args
          runpy.run_path("post_kld.py", run_name="__main__")
          PY
