#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
gen_lunar_calendar.py
~~~~~~~~~~~~~~~~~~~~~
Генерирует lunar_calendar.json для текущего месяца с точными расчётами:
  - phase         : "Полнолуние в Овне (100% освещ.)"
  - phase_time    : ISO-время UT момента фазы
  - percent       : 100
  - sign          : "Овен"
  - aspects       : ["☌Saturn (+0.4°)", …]
  - void_of_course: {"start":"DD.MM HH:mm","end":"DD.MM HH:mm"}
  - next_event    : "→ Через 2 дн. Новолуние в Близнецах"
  - advice        : ["…","…","…"]
  - favorable_days / unfavorable_days
"""

import os, json, math, random
from pathlib import Path
from typing import Dict, Any, List

import pendulum
import swisseph as swe

# ── Опциональный GPT-клиент ───────────────────────────────
try:
    from openai import OpenAI
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
except ImportError:
    client = None

# ── Временная зона для форматирования Void-of-Course ────────
TZ = pendulum.timezone("UTC")

# ── Категории дней ────────────────────────────────────────
CATEGORIES = {
    "general":  {"favorable":[1,2,3,4,7,28,29], "unfavorable":[13,20,23,24,27]},
    "haircut":  {"favorable":[1,2,4,7,9,10,18,19,24,25,31], "unfavorable":[]},
    "travel":   {"favorable":[5,7,14,15],            "unfavorable":[]},
    "shopping": {"favorable":[3,6,9,12,14,17,20,25], "unfavorable":[13,20,23,24,27]},
    "health":   {"favorable":[1,2,3,4,7,28,29],       "unfavorable":[]},
}

# ── Аспекты и орбисы ─────────────────────────────────────
ASPECTS = {0:"☌", 60:"⚹", 90:"□", 120:"△", 180:"☍"}
ORBIS   = {0:5.0, 60:4.0, 90:3.0, 120:4.0, 180:5.0}

PLANETS = {
    "Sun": swe.SUN, "Mercury": swe.MERCURY, "Venus": swe.VENUS,
    "Mars": swe.MARS, "Jupiter": swe.JUPITER, "Saturn": swe.SATURN,
    "Uranus": swe.URANUS, "Neptune": swe.NEPTUNE, "Pluto": swe.PLUTO,
}

# ── Фолбэк-советы по фазам ────────────────────────────────
FALLBACK = {
    "Новолуние": [
        "Работа/финансы: Запланируй цели месяца 📝☀️",
        "Здоровье: Пей воду с лимоном 💧🍋",
        "Ритуал: Медитация у моря 🧘🌊",
    ],
    # ... добавьте аналогично для других фаз
}

def jd_to_dt(jd: float) -> pendulum.DateTime:
    """JD → pendulum UTC"""
    return pendulum.from_timestamp((jd - 2440587.5) * 86400, tz=TZ)

def compute_phase_and_sign(jd: float):
    """Вычисляет название фазы, % освещённости и знак зодиака."""
    slon = swe.calc_ut(jd, swe.SUN)[0][0]
    mlon = swe.calc_ut(jd, swe.MOON)[0][0]
    angle = (mlon - slon) % 360
    pct = int(round((1 - math.cos(math.radians(angle))) / 2 * 100))
    if angle < 22.5 or angle >= 337.5:     name="Новолуние"
    elif angle < 67.5:                     name="Растущий серп"
    elif angle < 112.5:                    name="Первая четверть"
    elif angle < 157.5:                    name="Растущая Луна"
    elif angle < 202.5:                    name="Полнолуние"
    elif angle < 247.5:                    name="Убывающая Луна"
    elif angle < 292.5:                    name="Последняя четверть"
    else:                                  name="Убывающий серп"
    sign = ["Овен","Телец","Близнецы","Рак","Лев","Дева",
            "Весы","Скорпион","Стрелец","Козерог","Водолей","Рыбы"][int(mlon // 30)]
    return name, pct, sign

def next_phase_jd(jd: float, phase: str) -> float:
    """JD следующего события заданной фазы."""
    mapping = {
        "Новолуние": swe.next_new_moon,
        "Полнолуние": swe.next_full_moon,
        "Первая четверть": swe.next_first_quarter,
        "Последняя четверть": swe.next_last_quarter,
    }
    fn = mapping.get(phase, swe.next_new_moon)
    return fn(jd)

def compute_next_event(jd: float) -> str:
    """Кратко анонс ближайшего новолуния/полнолуния."""
    today = jd_to_dt(jd).date()
    jn = swe.next_new_moon(jd); dn = jd_to_dt(jn).date()
    jf = swe.next_full_moon(jd); df = jd_to_dt(jf).date()
    if (dn - today) <= (df - today):
        days, jd2 = (dn - today).days, jn
    else:
        days, jd2 = (df - today).days, jf
    ph, _, s = compute_phase_and_sign(jd2)
    return f"→ Через {days} дн. {ph} в {s}"

def compute_aspects(jd: float) -> List[str]:
    """Ищет основные аспекты Луны к планетам."""
    mlon = swe.calc_ut(jd, swe.MOON)[0][0]
    out = []
    for name, pid in PLANETS.items():
        pl = swe.calc_ut(jd, pid)[0][0]
        diff = abs((mlon - pl + 180) % 360 - 180)
        for ang, sym in ASPECTS.items():
            if abs(diff - ang) <= ORBIS[ang]:
                out.append(f"{sym}{name} ({diff-ang:+.1f}°)")
    return out

def compute_void_of_course(jd: float) -> Dict[str, str]:
    """Реальные интервалы Void-of-Course для Луны."""
    start_jd = swe.next_void(swe.MOON, jd)
    end_jd   = swe.next_enter(swe.MOON, jd)
    start_dt = jd_to_dt(start_jd).in_tz(TZ)
    end_dt   = jd_to_dt(end_jd).in_tz(TZ)
    return {
        "start": start_dt.format("DD.MM HH:mm"),
        "end":   end_dt.format("DD.MM HH:mm"),
    }

def compute_advice(date: pendulum.Date, phase: str) -> List[str]:
    """Три совета от GPT или фолбэк."""
    if client:
        prompt = (
            f"Действуй как астролог, дата {date}, фаза {phase}. "
            "Дай 3 совета (работа/финансы; что отложить; ритуал дня)."
        )
        resp = client.chat.completions.create(
            model="gpt-4o-mini", temperature=0.7,
            messages=[{"role":"user","content":prompt}]
        )
        lines = [ln.strip() for ln in resp.choices[0].message.content.splitlines() if ln.strip()]
        return lines[:3]
    base = FALLBACK.get(phase, FALLBACK["Новолуние"])
    return random.sample(base, k=3)

def generate_calendar(year: int, month: int) -> Dict[str, Any]:
    swe.set_ephe_path('.')  # путь к эфемеридам
    start = pendulum.date(year, month, 1)
    end   = start.end_of('month')
    cal = {}
    d = start
    while d <= end:
        jd = swe.julday(d.year, d.month, d.day, 0.0)
        name, pct, sign = compute_phase_and_sign(jd)
        # момент этой фазы
        jt = next_phase_jd(jd, name)
        cal[d.to_date_string()] = {
            "phase":           f"{name} в {sign} ({pct}% освещ.)",
            "phase_time":      jd_to_dt(jt).to_iso8601_string(),
            "percent":         pct,
            "sign":            sign,
            "aspects":         compute_aspects(jd),
            "void_of_course":  compute_void_of_course(jd),
            "next_event":      compute_next_event(jd),
            "advice":          compute_advice(d, name),
            "favorable_days":   {k:v["favorable"]   for k,v in CATEGORIES.items()},
            "unfavorable_days": {k:v["unfavorable"] for k,v in CATEGORIES.items()},
        }
        d = d.add(days=1)
    return cal

def main():
    today = pendulum.today()
    data  = generate_calendar(today.year, today.month)
    out   = Path(__file__).parent / "lunar_calendar.json"
    out.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"✅ lunar_calendar.json сгенерирован для {today.format('MMMM YYYY')}")

if __name__ == "__main__":
    main()
