name: Daily posts (CY + KLG)

on:
  schedule:
    - cron: '0 17 * * *'      # 17:00 UTC = 20:00 CY = 19:00 KLG
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region: [cy, klg]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: {python-version: '3.11'}

      - name: Export env per region
        run: |
          if [[ "${{ matrix.region }}" == "cy" ]]; then
            echo "BOT_NAME=cy"                >> $GITHUB_ENV
            echo "CHANNEL_ID=${{ secrets.CHANNEL_ID }}"          >> $GITHUB_ENV
            echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}"  >> $GITHUB_ENV
            echo 'SEA_CITIES=[]'              >> $GITHUB_ENV
            echo 'LAND_CITIES=[]'             >> $GITHUB_ENV
          else
            echo "BOT_NAME=klg"               >> $GITHUB_ENV
            echo "CHANNEL_ID=${{ secrets.CHANNEL_ID_KLG }}"      >> $GITHUB_ENV
            echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN_KLG }}" >> $GITHUB_ENV
            # --------- прям те списки, о которых вы просили -------------
            cat <<'JSON' >> $GITHUB_ENV
SEA_CITIES=[{"name":"Baltijsk","lat":54.65,"lon":19.95},
            {"name":"Svetlogorsk","lat":54.94,"lon":20.15},
            {"name":"Pionerskiy","lat":54.95,"lon":20.23},
            {"name":"Zelenogradsk","lat":54.96,"lon":20.48},
            {"name":"Yantarny","lat":54.87,"lon":19.93}]
LAND_CITIES=[{"name":"Guryevsk","lat":54.78,"lon":20.61},
             {"name":"Svetly","lat":54.68,"lon":20.14},
             {"name":"Sovetsk","lat":55.08,"lon":21.88},
             {"name":"Chernyakhovsk","lat":54.63,"lon":21.82},
             {"name":"Gusev","lat":54.59,"lon":22.20},
             {"name":"Neman","lat":55.03,"lon":22.03},
             {"name":"Mamonovo","lat":54.47,"lon":19.93},
             {"name":"Polessk","lat":54.86,"lon":21.10},
             {"name":"Bagrationovsk","lat":54.39,"lon":20.65},
             {"name":"Ladushkin","lat":54.57,"lon":20.15},
             {"name":"Pravdinsk","lat":54.45,"lon":21.01},
             {"name":"Slavsk","lat":55.04,"lon":21.67},
             {"name":"Ozyorsk","lat":54.40,"lon":22.00},
             {"name":"Nesterov","lat":54.63,"lon":22.55},
             {"name":"Krasnoznamensk","lat":55.05,"lon":22.49},
             {"name":"Gvardejsk","lat":54.65,"lon":21.07}]
JSON
          fi
      - run: python -m pip install -r requirements.txt
      - run: python post.py
