name: Radiation quick test

on:
  workflow_dispatch:   # запускается вручную из вкладки «Actions»

jobs:
  radiation-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Если в проекте уже есть requirements.txt — установим всё оттуда,
      # иначе просто requests (нужен radiation.py)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Sanity check get_radiation()
        run: |
          python - <<'PY'
          import logging, radiation
          logging.basicConfig(level=logging.INFO)

          # две контрольные точки: Калининград и Лимассол
          tests = {
              "Калининград": (54.71, 20.45),
              "Лимассол":    (34.70, 33.02),
          }

          for city, (lat, lon) in tests.items():
              print(f"\n— {city} ({lat}, {lon}) —")
              print(radiation.get_radiation(lat, lon))
          PY
